### ISSUE TITLE
Use single quotes instead of double quotes

### ISSUE THREAD

**Issue by nilsreichardt** [jeroen-meijer/pubspec-assist#143]
My `pubspec.yaml` looks something like this:
```yaml
name: my_package
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
```

When I'm now adding a new package, the extension will replace the `publish_to: 'none'` with `publish_to: "none"`.

```diff
name: my_package
description: A new Flutter project.
- publish_to: 'none'
+ publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
```

When running `flutter create my_package`, Flutter uses single quotes for the `publish_to` (in feature also for the `dartSdkVersionBounds`: https://github.com/flutter/flutter/pull/101270).

Would it be possible to use single quotes instead of double quotes?
