### ISSUE TITLE
[Feature Request] Sorting

### ISSUE THREAD

**Issue by JCKodel** [jeroen-meijer/pubspec-assist#19]
It would be nice if, after adding a package, the contents of pubspec.yaml is sorted.
I use https://github.com/Tyriar/vscode-sort-lines to do so, but is an extra step.

**Comment by jeroen-meijer** [comment]
I agree, this would be nice.
Thanks for the suggestion.

**Comment by jeroen-meijer** [comment]
Will implement this in the next version.

I was thinking of keeping the top-level order the same, but to sort all the `dependencies` and `dev_dependencies` by name.
Additionally, I want to sort them by order of:
1. Local packages
2. Hosted on other hosts (not pub.dev)
3. Rest (regular dependencies)

All alphabetically.

@JCKodel what do you think?

**Comment by JCKodel** [comment]
@jeroen-meijer That would be awesome. This separation between git, file and pub.dev is good (and actually is the way I work, using the https://github.com/Tyriar/vscode-sort-lines plugin (this plugin only sort lines, so dependencies such as git has to be done manually)

**Comment by jeroen-meijer** [comment]
Great. Working on this right now. Expect a release later today (2.1.0).

**Comment by jeroen-meijer** [comment]
Implemented. Sorting will now take place like this:
```yaml
dev_dependencies:
  flutter:
    sdk: "whatever"
  freezed:
    path: ../freezed
  zombies:
    git: https://.../zombies.git
  forrest:
    hosted: abcdef
  animations: 1.1.2
  get_it: 5.0.1
```
