### ISSUE TITLE
Adding package 'path' replaces path of existing package, if any

### ISSUE THREAD

**Issue by kentcb** [jeroen-meijer/pubspec-assist#22]
Given a pubspec like this:

```yaml
name: foo
description: Foo.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  local_package:
    path: ../local_package/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

```

Adding package `path` replaces the path of `local_package` rather than adding a new line.
