### ISSUE TITLE
Bug Report: Expected YAML collection at dev_dependencies. 

### ISSUE THREAD

**Issue by simphotonics** [jeroen-meijer/pubspec-assist#49]
Hello @jeroen-meijer, thank you for creating this very helpful package.

The above issue has been reported already but I'd like to add platform details to help reproduce the error:
```Console
$ dart --version
Dart SDK version: 2.9.0-21.10.beta (beta) (Tue Jul 21 10:46:30 2020 +0200) on "linux_x64"
``` 

The error occurs when the `dependencies` or `dev_dependencies` entries are initially empty:
```Yaml
name: quote_buffer
description:
  Extension on StringBuffer that simplifies transforming single objects and lists of objects
  into quoted strings.


version: 0.2.0
homepage: https://github.com/simphotonics/quote_buffer

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:

dev_dependencies:
```  

When selecting any package, e.g. pedantic, the following error message is shown:
`Pubspec Assist: A critical error has occurred. If this happens again, please report it.
 Error message: Expected YAML collection at dev_dependencies. Remaining path: pedantic`
