### ISSUE TITLE
Bug Report: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by maheshmnj** [jeroen-meijer/pubspec-assist#63]
firstly thanks for this great plugin but there seems to be a small issue with this plugin.

It fails to sort the dependencies if any of the dependencies do not have a version mentioned.
 the dependency section of my pubspec.yaml looks like this 

```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rxdart:
  http: ^0.12.2
```
