### ISSUE TITLE
[Feature Request] Maintain comments on sort

### ISSUE THREAD

**Issue by QuestofIranon** [jeroen-meijer/pubspec-assist#70]
As an extension to #19  it would be nice to maintain comments above the dependencies when sorting.

For example, I often leave comments to the documentation or a small description of what the dependency is being used for above the dependency (mainly for the sake of onboarding new developers or performing code review). Currently, when the sort is performed, those comments are cleared.

**Comment by KDCinfo** [comment]
All inline comments are removed as well. So I've begun copying all the lines that have comments and putting them above the list (commented out). These comments help because in VS Code, when you select a commented word on the right, all the same ones highlight giving you a nice visual association of related dependencies. 
```
# [Preserving Comments]:
# bloc_concurrency #          # BLoC
# bloc_test #                 # Testing
# equatable #                 # BLoC-helper
# flutter_app_badger #        # Notifications-related
# flutter_bloc #              # BLoC
# flutter_local_notifications # Notifications
# flutter_native_timezone #   # Notifications-related
# hydrated_bloc #             # BLoC
# notification_permissions #  # Notifications
# path_provider #             # BLoC-helper
# test #                      # Testing
#
dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  bloc_concurrency: ^0.1.0
  bloc_test: ^8.5.0
  ...
```
