### ISSUE TITLE
Bug Report: preserve whitespace within dependencies map

### ISSUE THREAD

**Issue by lukepighetti** [jeroen-meijer/pubspec-assist#77]
Let's say you have the following dependencies. Notice the whitespace.

```
dependencies:
  flutter:
    sdk: flutter

  my_dependency: ^1.0.0
```

If you add `my_new_dependency`, the whitespace is removed by `pubspec-assist`. All formatting should be respected and not overwritten.

```
dependencies:
  flutter:
    sdk: flutter
  my_dependency: ^1.0.0
  my_new_dependency: ^1.0.0
```
