### ISSUE TITLE
remove pubspec comments when add new dependency 

### ISSUE THREAD

**Issue by maxzod** [jeroen-meijer/pubspec-assist#91]
the original yaml file
```yaml
name: three_core
description: A new Flutter package project.
version: 0.0.1
author: Ahmed Masoud

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # database
  cloud_firestore: ^1.0.3
  
  # auth
  firebase_auth: ^1.0.1

dev_dependencies:
  lint: ^1.5.3
```

after add logger package
```yaml
name: three_core
description: A new Flutter package project.
version: 0.0.1
author: Ahmed Masoud

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.3
  firebase_auth: ^1.0.1
  logger: ^1.0.0

dev_dependencies:
  lint: ^1.5.3

```
